# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

Message.create(user_id: 1, title: 'test title 1', content: 'test content 1')
Message.create(user_id: 2, title: 'test title 2', content: 'test content 2')
Message.create(user_id: 3, title: 'test title 3', content: 'test content 3')
Message.create(user_id: 5, title: 'test title 1', content: 'test content 1')
Message.create(user_id: 6, title: 'test title 2', content: 'test content 2')
Message.create(user_id: 7, title: 'test title 3', content: 'test content 3')
Message.create(user_id: 8, title: 'test title 1', content: 'test content 1')
Message.create(user_id: 9, title: 'test title 2', content: 'test content 2')
Message.create(user_id: 10, title: 'test title 3', content: 'test content 3')
Message.create(user_id: 11, title: 'test title 1', content: 'test content 1')
Message.create(user_id: 12, title: 'test title 2', content: 'test content 2')
Message.create(user_id: 13, title: 'test title 3', content: 'test content 3')
Message.create(user_id: 14, title: 'test title 1', content: 'test content 1')
Message.create(user_id: 15, title: 'test title 2', content: 'test content 2')
Message.create(user_id: 16, title: 'test title 3', content: 'test content 3')
Message.create(user_id: 17, title: 'test title 1', content: 'test content 1')
Message.create(user_id: 18, title: 'test title 2', content: 'test content 2')
Message.create(user_id: 19, title: 'test title 3', content: 'test content 3')
Message.create(user_id: 20, title: 'test title 1', content: 'test content 1')
Message.create(user_id: 21, title: 'test title 2', content: 'test content 2')
Message.create(user_id: 22, title: 'test title 3', content: 'test content 3')
Message.create(user_id: 23, title: 'test title 1', content: 'test content 1')
Message.create(user_id: 24, title: 'test title 2', content: 'test content 2')
Message.create(user_id: 25, title: 'test title 3', content: 'test content 3')
Message.create(user_id: 26, title: 'test title 1', content: 'test content 1')
Message.create(user_id: 27, title: 'test title 2', content: 'test content 2')
Message.create(user_id: 28, title: 'test title 3', content: 'test content 3')
Message.create(user_id: 29, title: 'test title 1', content: 'test content 1')
Message.create(user_id: 30, title: 'test title 2', content: 'test content 2')